// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAx6O-jsV_TMjgP_qnkNCLhG6mTdNSN_A',
    appId: '1:5826002464:web:cfab05d0d259d2ed194645',
    messagingSenderId: '5826002464',
    projectId: 'aminhabiblia-558d1',
    authDomain: 'aminhabiblia-558d1.firebaseapp.com',
    storageBucket: 'aminhabiblia-558d1.firebasestorage.app',
    measurementId: 'G-7RY04CNT1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChRNj8umfbo_ZXiQ0j8AA9x83BOQBIgL0',
    appId: '1:5826002464:android:822322637548900d194645',
    messagingSenderId: '5826002464',
    projectId: 'aminhabiblia-558d1',
    storageBucket: 'aminhabiblia-558d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmukPtzOkWiIg8P140CmHvyNrjifuRbcg',
    appId: '1:5826002464:ios:91b367bf2ee95d96194645',
    messagingSenderId: '5826002464',
    projectId: 'aminhabiblia-558d1',
    storageBucket: 'aminhabiblia-558d1.firebasestorage.app',
    iosBundleId: 'com.example.bibliaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmukPtzOkWiIg8P140CmHvyNrjifuRbcg',
    appId: '1:5826002464:ios:91b367bf2ee95d96194645',
    messagingSenderId: '5826002464',
    projectId: 'aminhabiblia-558d1',
    storageBucket: 'aminhabiblia-558d1.firebasestorage.app',
    iosBundleId: 'com.example.bibliaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAx6O-jsV_TMjgP_qnkNCLhG6mTdNSN_A',
    appId: '1:5826002464:web:e4d8133cd4eb4099194645',
    messagingSenderId: '5826002464',
    projectId: 'aminhabiblia-558d1',
    authDomain: 'aminhabiblia-558d1.firebaseapp.com',
    storageBucket: 'aminhabiblia-558d1.firebasestorage.app',
    measurementId: 'G-LJL2WBBGVT',
  );
}
